### ISSUE TITLE
Notices with ThumbnailUpdater setNewMetadata

### ISSUE THREAD

**Issue by rbaugh** [short-pixel-optimizer/enable-media-replace#28] opened 2019-03-29 15:13 UTC
Should there be a check in place for the two calls to the thumbnailUpdater to make sure the file being managed is an actual image?
https://github.com/short-pixel-optimizer/enable-media-replace/blob/master/upload.php#L234
https://github.com/short-pixel-optimizer/enable-media-replace/blob/master/upload.php#L387

Here are the notice warnings I got when replacing a PDF file:
[29-Mar-2019 13:49:13 UTC] PHP Stack trace:
[29-Mar-2019 13:49:13 UTC] PHP   1. {main}() /var/www/public_html/wp/wp-login.php:0
[29-Mar-2019 13:54:13 UTC] PHP Notice:  Undefined index: file in /var/www/public_html/wp-content/plugins/enable-media-replace/thumbnail_updater.php on line 44
[29-Mar-2019 13:54:13 UTC] PHP Stack trace:
[29-Mar-2019 13:54:13 UTC] PHP   1. {main}() /var/www/public_html/wp/wp-admin/upload.php:0
[29-Mar-2019 13:54:13 UTC] PHP   2. require_once() /var/www/public_html/wp/wp-admin/upload.php:10
[29-Mar-2019 13:54:13 UTC] PHP   3. do_action() /var/www/public_html/wp/wp-admin/admin.php:224
[29-Mar-2019 13:54:13 UTC] PHP   4. WP_Hook->do_action() /var/www/public_html/wp/wp-includes/plugin.php:453
[29-Mar-2019 13:54:13 UTC] PHP   5. WP_Hook->apply_filters() /var/www/public_html/wp/wp-includes/class-wp-hook.php:310
[29-Mar-2019 13:54:13 UTC] PHP   6. emr_options() /var/www/public_html/wp/wp-includes/class-wp-hook.php:286
[29-Mar-2019 13:54:13 UTC] PHP   7. require_once() /var/www/public_html/wp-content/plugins/enable-media-replace/enable-media-replace.php:113
[29-Mar-2019 13:54:13 UTC] PHP   8. ThumbnailUpdater->setNewMetadata() /var/www/public_html/wp-content/plugins/enable-media-replace/upload.php:387
[29-Mar-2019 13:54:13 UTC] PHP Notice:  Undefined index: file in /var/www/public_html/wp-content/plugins/enable-media-replace/thumbnail_updater.php on line 45
[29-Mar-2019 13:54:13 UTC] PHP Stack trace:
[29-Mar-2019 13:54:13 UTC] PHP   1. {main}() /var/www/public_html/wp/wp-admin/upload.php:0
[29-Mar-2019 13:54:13 UTC] PHP   2. require_once() /var/www/public_html/wp/wp-admin/upload.php:10
[29-Mar-2019 13:54:13 UTC] PHP   3. do_action() /var/www/public_html/wp/wp-admin/admin.php:224
[29-Mar-2019 13:54:13 UTC] PHP   4. WP_Hook->do_action() /var/www/public_html/wp/wp-includes/plugin.php:453
[29-Mar-2019 13:54:13 UTC] PHP   5. WP_Hook->apply_filters() /var/www/public_html/wp/wp-includes/class-wp-hook.php:310
[29-Mar-2019 13:54:13 UTC] PHP   6. emr_options() /var/www/public_html/wp/wp-includes/class-wp-hook.php:286
[29-Mar-2019 13:54:13 UTC] PHP   7. require_once() /var/www/public_html/wp-content/plugins/enable-media-replace/enable-media-replace.php:113
[29-Mar-2019 13:54:13 UTC] PHP   8. ThumbnailUpdater->setNewMetadata() /var/www/public_html/wp-content/plugins/enable-media-replace/upload.php:387

**Comment by pdobrescu** [comment] 2020-10-29 08:39
hi @rbaugh and thanks for reporting this issue. As the plugin has several releases since this issue was added, I will close it for now.

In case you still get these Notices, please re-open the issue and give us more details, as I wasn't able to reproduce them.

**Closed by pdobrescu** 2020-10-29 08:39 UTC
