### ISSUE TITLE
Replacing image does not update metadata for asset

### ISSUE THREAD

**Issue by Zxurian** [short-pixel-optimizer/enable-media-replace#91] opened 2023-03-15 16:25 UTC
Using v4.0.3

When replacing an asset with a larger asset, the meta data is not updated within Wordpress. I have verified that the new asset _is_ being uploaded and parsed, as the thumbnails are correctly regenerated, and by copying the File URL into a new tab, it does show the new asset at the larger dimensions, but the original image metadata is not updated.

This can also be seen when looking at the attachment metadata after uploading. 
```
array (
  'width' => 1280,
  'height' => 700,
  'file' => '2016/05/grey-felt-screen-with-circles-cut-out-suspended-in-lounge-area-scaled.jpg',
  'filesize' => 727732,
  'sizes' => 
  array( ... ),
  'image_meta' => 
  array (
    'aperture' => '0',
    'credit' => '',
    'camera' => '',
    'caption' => '',
    'created_timestamp' => '0',
    'copyright' => '',
    'focal_length' => '0',
    'iso' => '0',
    'shutter_speed' => '0',
    'title' => '',
    'orientation' => '0',
    'keywords' => 
    array (
    ),
  ),
  'original_image' => 'grey-felt-screen-with-circles-cut-out-suspended-in-lounge-area.jpg',
)
```
It's still showing the original image data, not the new image data, which should be:
```
  'width' => 3000,
  'height' => 2086,
  'file' => '2016/05/grey-felt-screen-with-circles-cut-out-suspended-in-lounge-area-scaled.jpg',
  'filesize' => 2704020,
  
```
![image](https://user-images.githubusercontent.com/573371/225374261-f7b8e78f-0f73-4c04-90a0-61e2018c1835.png)

**Comment by pdobrescu** [comment] 2023-03-15 19:55
hello @Zxurian and thanks for reporting this issue! I ran a few tests and couldn't reproduce this issue. In other words, when doing a replace (either with `Just replace the file` or `Replace the file, use the new file name, and update all links` the meta data flagged in the above image gets updated correctly. I, therefore, suspect there might be something else interfering with our plugin's functionality.

Are you able to test this on a site where only our plugin is active and a standard WordPress theme, to see if you can reproduce it? If it works, then you'll probably have to take the active plugins (and the theme) one by one and deactivate them until you find the one interfering. In case you're able to still reproduce it, please send us the 2 images that you're using, as well as the options you're using when doing the replace.

**Comment by Zxurian** [comment] 2023-03-15 23:52
I have a test site I can test with _just_ standard WP Core & Enable Media Replace. I'll use the same image to reproduce and document steps.
Currently we have two plugins that work with images, so it may be a matter of how it interacts with those plugins. Kraken Image Optimizer, & Infinity Uploads.
I will perform some diagnostics with different enablements to see what series of combination / steps reproduces the issue.

**Comment by pdobrescu** [comment] 2023-03-27 10:55
hello @Zxurian, can you please check if you are still encountering the issue without other active plugins? We are preparing to release a new version this week and if a fix is required, I'd like to include it in this release. Thanks!

**Comment by pdobrescu** [comment] 2023-12-08 12:18
Dear @Zxurian, apologies for getting back to you on this so late. 

I looked over the screenshots you sent and noticed something that drew my attention. I'm talking about the slashes from [this screenshot](https://i.imgur.com/qj2seiT.png):

![image](https://github.com/short-pixel-optimizer/enable-media-replace/assets/1044106/ff477b80-cc48-4836-93c8-54ae923d28ad)

Something doesn't seem right in that path, using both backslashes and forwardslashes. Are you by any chance running WordPress on a Windows environment/server? While I've seen sites running (and our plugin functioning correctly with Windows-style paths), this is the first time I've seen both backslashes and forwardslashes in a path. I'm pretty sure this is the reason behind the errors you're seeing.

**Comment by pdobrescu** [comment] 2024-08-30 16:45
Closing, as we haven't got any updates here. If there are still errors, please reopen this issue.

**Closed by pdobrescu** 2024-08-30 16:45 UTC
